import 'package:qr_flutter/qr_flutter.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'dart:typed_data';
import 'dart:developer';

//TODO: implement localization

class QrCodeGenerator {

  static Future<ByteData?> generateQrImageData(String uri, {double size = 200.0}) async {
    return await QrPainter(
      data: uri,
      version: QrVersions.auto,
      gapless: false,
    ).toImageData(size);
  }

  static Future<void> printQrCode(String title, String uri, {String? hint}) async {
    final doc = pw.Document();
    
    final ByteData? qrImageData = await generateQrImageData(uri, size: 500);
    if (qrImageData == null) {
      log("Error generating QR image data for printing.");
      return;
    }
    final Uint8List qrBytes = qrImageData.buffer.asUint8List();

    doc.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 20),
                pw.Container(
                  width: 250,
                  height: 250,
                  child: pw.Image(pw.MemoryImage(qrBytes)),
                ),
                pw.SizedBox(height: 10),
                if (hint != null && hint.isNotEmpty)
                  pw.Text("Hint: $hint", style: pw.TextStyle(fontSize: 12, fontStyle: pw.FontStyle.italic)),
                pw.Spacer(),
                pw.Text("Generated by QRVault", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
              ]
            ),
          );
        }));
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => doc.save());
  }
}  

